# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: file-creator@5
  inputs:
    fileoverwrite: true
    filepath: 'ProjectSIP/ClientApp/src/environments/environment.ts'
    filecontent: |
      export class environment = {
        production: false,
        baseApiUrl: ''
      };
    endWithNewLine: true

- task: file-creator@5
  inputs:
    fileoverwrite: true
    filepath: 'ProjectSIP/ClientApp/src/environments/environment.prod.ts'
    filecontent: |
      export class environment = {
        production: true,
        baseApiUrl: ''
      };
    endWithNewLine: true

- script: cd $(Build.ArtifactStagingDirectory) && dotnet tool restore
  displayName: 'dotnet tool restore'

- script: dotnet swagger tofile --output '$(Build.ArtifactStagingDirectory)/ClientApp/swagger.json' "$(Build.ArtifactStagingDirectory)/ProjectSIP.dll" v1
  displayName: 'dotnet swagger tofile'

- script: dotnet publish --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'project-sip-build'

- task: CopyFiles@2
  displayName: 'Copy deploy artifact'
  inputs:
    SourceFolder: 'Deploy'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: project-sip-deploy'
  inputs:
    ArtifactName: 'project-sip-deploy'